export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_EMPTY = "CART_EMPTY";
export const CART_DRAWER = "CART_DRAWER";

export const COUPON_APPLIED_SUCCESS = "COUPON_APPLIED_SUCCESS";
export const COUPON_APPLIED_RESET = "COUPON_APPLIED_RESET";
