export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL";
export const SEARCH_PRODUCT_RESET = "SEARCH_PRODUCT_RESET";

export const SEARCH_QUERY = "SEARCH_QUERY";
export const SEARCH_QUERY_RESET = "SEARCH_QUERY_RESET";
